import { NET_WORTH_STATEMENT_ENTRIES } from './NetWorthPositioningPage'

export function calculateFinancialStatementCompletion(
  values: Record<string, string>,
  prefix = '',
): number {
  const requiredEntries = NET_WORTH_STATEMENT_ENTRIES.filter((entry) => !entry.autoGenerated)
  const completedEntries = requiredEntries.filter((entry) => {
    const value = values[`${prefix}${entry.id}`]
    return value !== undefined && value.trim() !== ''
  })
  return Math.round((completedEntries.length / requiredEntries.length) * 100)
}