export const BUILD_PROFILE_STORAGE_KEY = 'fms:build-profile'

export type ReplicatedBuildProfile = {
  profileId: string
  updatedAt?: string
  values: Record<string, string>
  documents: string[]
  suitabilityAnswers: Record<string, string>
  coBorrowers: Array<Record<string, string>>
  guarantors: Array<Record<string, string>>
  additionalCollaterals: Array<Record<string, string>>
}

type StatementEntry = {
  id: string
  label: string
  section: string
  category: string
  autoGenerated?: boolean
}

export type ReplicatedNetWorthDraft = {
  asOfDate: string
  currency: string
  selectedFinancialGoal: string
  targetAmount: number
  targetMonths: number
  amounts: Record<string, string>
  monthlyExpenseAllocationDraft: Record<string, string>
  savedSetup: Array<{ id: string; label: string; section: string; category: string; setupAmount: number }>
  suitabilityAnswers: Record<string, number>
  actualEntries: Record<string, string>
  varianceNotes: Record<string, string>
}

export function readReplicatedBuildProfile(expectedId?: string): ReplicatedBuildProfile | null {
  if (typeof window === 'undefined') return null
  try {
    const parsed = JSON.parse(window.localStorage.getItem(BUILD_PROFILE_STORAGE_KEY) || 'null') as ReplicatedBuildProfile | null
    if (!parsed?.profileId || !parsed.values || (expectedId && parsed.profileId !== expectedId)) return null
    return parsed
  } catch {
    return null
  }
}

export function toNetWorthDraft(
  profile: ReplicatedBuildProfile,
  statementEntries: StatementEntry[],
): ReplicatedNetWorthDraft {
  const editableEntries = statementEntries.filter((entry) => !entry.autoGenerated)
  const amounts = Object.fromEntries(editableEntries.map((entry) => [entry.id, profile.values[entry.id] ?? '']))
  const positiveEntries = editableEntries.filter((entry) => Number(amounts[entry.id] || 0) > 0)

  return {
    asOfDate: profile.values.asOfDate ?? '',
    currency: profile.values.wealthCurrency || 'PHP',
    selectedFinancialGoal: profile.values.financialGoal ?? '',
    targetAmount: Number(profile.values.targetAmount) || 0,
    targetMonths: Number(profile.values.targetMonths) || 12,
    amounts,
    monthlyExpenseAllocationDraft: Object.fromEntries(editableEntries.map((entry) => [entry.id, profile.values[`wealthAllocation.${entry.id}`] ?? ''])),
    savedSetup: profile.values.wealthSetupSaved === 'true'
      ? positiveEntries.map((entry) => ({ ...entry, setupAmount: Number(amounts[entry.id]) }))
      : [],
    suitabilityAnswers: Object.fromEntries(Object.entries(profile.suitabilityAnswers).map(([key, value]) => [key, Number(value) || 0])),
    actualEntries: Object.fromEntries(editableEntries.map((entry) => [entry.id, profile.values[`wealthActual.${entry.id}`] ?? ''])),
    varianceNotes: Object.fromEntries(editableEntries.map((entry) => [entry.id, profile.values[`wealthVarianceNote.${entry.id}`] ?? ''])),
  }
}