import { useCallback, useEffect, useMemo, useState } from 'react';

import {
  fetchAutosaveDraft,
  isAutosaveConflictError,
  saveAutosaveDraftRemote,
} from '../../autosave/draftApi';
import { useLoanApplicationsMetrics } from '../../hooks/useLoanApplicationsMetrics';
import { buildNetWorthPositioningSnapshot } from './liveTrackerMetrics';

type WorkflowStep = 1 | 2 | 3;
type StatementSection =
  | 'assets'
  | 'liabilities'
  | 'monthly-income'
  | 'monthly-expenses'
  | 'financial-goals'
  | 'insurance-coverage'
  | 'ai-analysis';

type StatementEntry = {
  id: string;
  label: string;
  section: StatementSection;
  category: string;
  autoGenerated?: boolean;
};

type SavedLine = {
  id: string;
  label: string;
  section: StatementSection;
  category: string;
  setupAmount: number;
};

interface NetWorthPositioningDraft {
  step: WorkflowStep;
  asOfDate: string;
  currency: string;
  currencyCode?: string;
  selectedFinancialGoal: string;
  amounts: Record<string, string>;
  monthlyExpenseAllocationDraft: Record<string, string>;
  savedSetup: SavedLine[];
  actualEntries: Record<string, string>;
  varianceNotes: Record<string, string>;
}

const DEFAULT_NET_WORTH_POSITIONING_DRAFT: NetWorthPositioningDraft = {
  step: 1,
  asOfDate: '',
  currency: 'PHP',
  selectedFinancialGoal: '',
  amounts: {},
  monthlyExpenseAllocationDraft: {},
  savedSetup: [],
  actualEntries: {},
  varianceNotes: {},
};

const FINANCIAL_GOAL_OPTIONS = [
  'Build Emergency Fund',
  'Pay off High Interest Debt',
  'Save for Major Purchase (10k above)',
  'Create Monthly Discipline',
  'Save for Property Down Payment',
  'Fund Education or Certification',
  'Grow an Investment Portfolio',
  'Establish Insurance Coverage',
  'Create Generational Wealth',
  'Support Social Responsibility',
  'Achieve Financial Independence',
  'Build Retirement Savings',
  'Others',
] as const;

const CURRENCY_OPTIONS = [
  { code: 'PHP', label: 'PHP (₱)' },
  { code: 'USD', label: 'USD ($)' },
  { code: 'EUR', label: 'EUR (€)' },
  { code: 'JPY', label: 'JPY (¥)' },
  { code: 'SGD', label: 'SGD (S$)' },
] as const;

const NET_WORTH_STATEMENT_ENTRIES: StatementEntry[] = [
  { id: 'asset-cash-on-hand', label: 'Cash on Hand', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-savings-account', label: 'Savings Account', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-checking-account', label: 'Checking Account', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-payroll-account', label: 'Payroll Account', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-time-deposit', label: 'Time Deposit', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-foreign-currency-account', label: 'Foreign Currency Account', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-digital-wallet', label: 'Digital Wallet (GCash, Maya, etc.)', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-emergency-fund', label: 'Emergency Fund', section: 'assets', category: '1. Cash & Bank Accounts' },
  { id: 'asset-stocks', label: 'Stocks', section: 'assets', category: '2. Investments' },
  { id: 'asset-mutual-funds', label: 'Mutual Funds', section: 'assets', category: '2. Investments' },
  { id: 'asset-uitf', label: 'UITF', section: 'assets', category: '2. Investments' },
  { id: 'asset-etfs', label: 'ETFs', section: 'assets', category: '2. Investments' },
  { id: 'asset-bonds', label: 'Bonds', section: 'assets', category: '2. Investments' },
  { id: 'asset-treasury-bills', label: 'Treasury Bills', section: 'assets', category: '2. Investments' },
  { id: 'asset-reits', label: 'REITs', section: 'assets', category: '2. Investments' },
  { id: 'asset-cryptocurrency', label: 'Cryptocurrency', section: 'assets', category: '2. Investments' },
  { id: 'asset-gold-precious-metals', label: 'Gold & Precious Metals', section: 'assets', category: '2. Investments' },
  { id: 'asset-other-investments', label: 'Other Investments', section: 'assets', category: '2. Investments' },
  { id: 'asset-retirement-fund', label: 'Retirement Fund', section: 'assets', category: '3. Retirement & Pension' },
  { id: 'asset-pension-benefits', label: 'Pension Benefits', section: 'assets', category: '3. Retirement & Pension' },
  { id: 'asset-provident-fund', label: 'Provident Fund', section: 'assets', category: '3. Retirement & Pension' },
  { id: 'asset-employer-retirement-plan', label: 'Employer Retirement Plan', section: 'assets', category: '3. Retirement & Pension' },
  { id: 'asset-primary-residence', label: 'Primary Residence', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-secondary-home', label: 'Secondary Home', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-condominium', label: 'Condominium', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-apartment-building', label: 'Apartment Building', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-commercial-property', label: 'Commercial Property', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-vacant-lot', label: 'Vacant Lot', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-agricultural-land', label: 'Agricultural Land', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-rental-property', label: 'Rental Property', section: 'assets', category: '4. Real Estate' },
  { id: 'asset-car', label: 'Car', section: 'assets', category: '5. Vehicles' },
  { id: 'asset-suv', label: 'SUV', section: 'assets', category: '5. Vehicles' },
  { id: 'asset-motorcycle', label: 'Motorcycle', section: 'assets', category: '5. Vehicles' },
  { id: 'asset-truck', label: 'Truck', section: 'assets', category: '5. Vehicles' },
  { id: 'asset-boat', label: 'Boat', section: 'assets', category: '5. Vehicles' },
  { id: 'asset-other-vehicles', label: 'Other Vehicles', section: 'assets', category: '5. Vehicles' },
  { id: 'asset-sole-proprietorship', label: 'Sole Proprietorship', section: 'assets', category: '6. Business Interests' },
  { id: 'asset-partnership-interest', label: 'Partnership Interest', section: 'assets', category: '6. Business Interests' },
  { id: 'asset-corporation-shares', label: 'Corporation Shares', section: 'assets', category: '6. Business Interests' },
  { id: 'asset-franchise-business', label: 'Franchise Business', section: 'assets', category: '6. Business Interests' },
  { id: 'asset-online-business', label: 'Online Business', section: 'assets', category: '6. Business Interests' },
  { id: 'asset-whole-life-insurance', label: 'Whole Life Insurance', section: 'assets', category: '7. Insurance with Cash Value' },
  { id: 'asset-investment-linked-insurance', label: 'Investment-Linked Insurance', section: 'assets', category: '7. Insurance with Cash Value' },
  { id: 'asset-annuities', label: 'Annuities', section: 'assets', category: '7. Insurance with Cash Value' },
  { id: 'asset-jewelry', label: 'Jewelry', section: 'assets', category: '8. Valuable Personal Assets' },
  { id: 'asset-watches', label: 'Watches', section: 'assets', category: '8. Valuable Personal Assets' },
  { id: 'asset-artwork', label: 'Artwork', section: 'assets', category: '8. Valuable Personal Assets' },
  { id: 'asset-collectibles', label: 'Collectibles', section: 'assets', category: '8. Valuable Personal Assets' },
  { id: 'asset-luxury-items', label: 'Luxury Items', section: 'assets', category: '8. Valuable Personal Assets' },
  { id: 'asset-electronics', label: 'Electronics', section: 'assets', category: '8. Valuable Personal Assets' },
  { id: 'asset-loans-receivable', label: 'Loans Receivable', section: 'assets', category: '9. Receivables' },
  { id: 'asset-salary-receivable', label: 'Salary Receivable', section: 'assets', category: '9. Receivables' },
  { id: 'asset-rental-receivable', label: 'Rental Receivable', section: 'assets', category: '9. Receivables' },
  { id: 'asset-other-receivables', label: 'Other Receivables', section: 'assets', category: '9. Receivables' },
  { id: 'asset-security-deposits', label: 'Security Deposits', section: 'assets', category: '10. Other Assets' },
  { id: 'asset-tax-refunds', label: 'Tax Refunds', section: 'assets', category: '10. Other Assets' },
  { id: 'asset-intellectual-property', label: 'Intellectual Property', section: 'assets', category: '10. Other Assets' },
  { id: 'asset-other-assets', label: 'Other Assets', section: 'assets', category: '10. Other Assets' },

  { id: 'liability-home-mortgage', label: 'Home Mortgage', section: 'liabilities', category: 'Housing Loans' },
  { id: 'liability-housing-loan', label: 'Housing Loan', section: 'liabilities', category: 'Housing Loans' },
  { id: 'liability-pagibig-housing-loan', label: 'Pag-IBIG Housing Loan', section: 'liabilities', category: 'Housing Loans' },
  { id: 'liability-car-loan', label: 'Car Loan', section: 'liabilities', category: 'Vehicle Loans' },
  { id: 'liability-motorcycle-loan', label: 'Motorcycle Loan', section: 'liabilities', category: 'Vehicle Loans' },
  { id: 'liability-commercial-vehicle-loan', label: 'Commercial Vehicle Loan', section: 'liabilities', category: 'Vehicle Loans' },
  { id: 'liability-personal-loan', label: 'Personal Loan', section: 'liabilities', category: 'Personal Loans' },
  { id: 'liability-salary-loan', label: 'Salary Loan', section: 'liabilities', category: 'Personal Loans' },
  { id: 'liability-emergency-loan', label: 'Emergency Loan', section: 'liabilities', category: 'Personal Loans' },
  { id: 'liability-multi-purpose-loan', label: 'Multi-Purpose Loan', section: 'liabilities', category: 'Personal Loans' },
  { id: 'liability-business-loan', label: 'Business Loan', section: 'liabilities', category: 'Business Loans' },
  { id: 'liability-working-capital-loan', label: 'Working Capital Loan', section: 'liabilities', category: 'Business Loans' },
  { id: 'liability-equipment-loan', label: 'Equipment Loan', section: 'liabilities', category: 'Business Loans' },
  { id: 'liability-credit-card-balance', label: 'Credit Card Balance', section: 'liabilities', category: 'Credit Obligations' },
  { id: 'liability-bnpl', label: 'Buy Now Pay Later (BNPL)', section: 'liabilities', category: 'Credit Obligations' },
  { id: 'liability-credit-line', label: 'Credit Line', section: 'liabilities', category: 'Credit Obligations' },
  { id: 'liability-sss-loan', label: 'SSS Loan', section: 'liabilities', category: 'Government Loans' },
  { id: 'liability-gsis-loan', label: 'GSIS Loan', section: 'liabilities', category: 'Government Loans' },
  { id: 'liability-pagibig-multi-purpose-loan', label: 'Pag-IBIG Multi-Purpose Loan', section: 'liabilities', category: 'Government Loans' },
  { id: 'liability-government-assistance-loan', label: 'Government Assistance Loan', section: 'liabilities', category: 'Government Loans' },
  { id: 'liability-student-loan', label: 'Student Loan', section: 'liabilities', category: 'Education Loans' },
  { id: 'liability-educational-assistance-loan', label: 'Educational Assistance Loan', section: 'liabilities', category: 'Education Loans' },
  { id: 'liability-hospital-bills', label: 'Hospital Bills', section: 'liabilities', category: 'Medical Obligations' },
  { id: 'liability-medical-loan', label: 'Medical Loan', section: 'liabilities', category: 'Medical Obligations' },
  { id: 'liability-taxes-payable', label: 'Taxes Payable', section: 'liabilities', category: 'Taxes & Other Payables' },
  { id: 'liability-utility-bills-due', label: 'Utility Bills Due', section: 'liabilities', category: 'Taxes & Other Payables' },
  { id: 'liability-insurance-premium-due', label: 'Insurance Premium Due', section: 'liabilities', category: 'Taxes & Other Payables' },
  { id: 'liability-accounts-payable', label: 'Accounts Payable', section: 'liabilities', category: 'Taxes & Other Payables' },
  { id: 'liability-loans-family-friends', label: 'Loans from Family/Friends', section: 'liabilities', category: 'Taxes & Other Payables' },
  { id: 'liability-other-liabilities', label: 'Other Liabilities', section: 'liabilities', category: 'Taxes & Other Payables' },

  { id: 'income-salary', label: 'Salary', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-business', label: 'Business Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-professional-fees', label: 'Professional Fees', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-freelance', label: 'Freelance Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-commission', label: 'Commission', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-rental', label: 'Rental Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-dividend', label: 'Dividend Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-interest', label: 'Interest Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-pension', label: 'Pension Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-government-benefits', label: 'Government Benefits', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-overseas', label: 'Overseas Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-agricultural', label: 'Agricultural Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-online', label: 'Online Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-passive', label: 'Passive Income', section: 'monthly-income', category: 'C. Monthly Income' },
  { id: 'income-other', label: 'Other Income', section: 'monthly-income', category: 'C. Monthly Income' },

  { id: 'expense-housing', label: 'Housing', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-utilities', label: 'Utilities', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-groceries', label: 'Groceries', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-dining', label: 'Dining', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-transportation', label: 'Transportation', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-fuel', label: 'Fuel', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-communications', label: 'Communications', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-internet', label: 'Internet', section: 'monthly-expenses', category: 'Living Expenses' },
  { id: 'expense-education', label: 'Education', section: 'monthly-expenses', category: 'Family Expenses' },
  { id: 'expense-childcare', label: 'Childcare', section: 'monthly-expenses', category: 'Family Expenses' },
  { id: 'expense-medical', label: 'Medical', section: 'monthly-expenses', category: 'Family Expenses' },
  { id: 'expense-household-help', label: 'Household Help', section: 'monthly-expenses', category: 'Family Expenses' },
  { id: 'expense-family-support', label: 'Family Support', section: 'monthly-expenses', category: 'Family Expenses' },
  { id: 'expense-loan-payments', label: 'Loan Payments', section: 'monthly-expenses', category: 'Financial Commitments' },
  { id: 'expense-credit-card-payments', label: 'Credit Card Payments', section: 'monthly-expenses', category: 'Financial Commitments' },
  { id: 'expense-insurance-premiums', label: 'Insurance Premiums', section: 'monthly-expenses', category: 'Financial Commitments' },
  { id: 'expense-taxes', label: 'Taxes', section: 'monthly-expenses', category: 'Financial Commitments' },
  { id: 'expense-investments', label: 'Investments', section: 'monthly-expenses', category: 'Financial Commitments' },
  { id: 'expense-retirement-savings', label: 'Retirement Savings', section: 'monthly-expenses', category: 'Financial Commitments' },
  { id: 'expense-entertainment', label: 'Entertainment', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-shopping', label: 'Shopping', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-travel', label: 'Travel', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-subscriptions', label: 'Subscriptions', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-gym-wellness', label: 'Gym & Wellness', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-hobbies', label: 'Hobbies', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-donations', label: 'Donations', section: 'monthly-expenses', category: 'Lifestyle' },
  { id: 'expense-miscellaneous', label: 'Miscellaneous', section: 'monthly-expenses', category: 'Lifestyle' },

  { id: 'goal-emergency-fund', label: 'Emergency Fund', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-home-purchase', label: 'Home Purchase', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-vehicle-purchase', label: 'Vehicle Purchase', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-education-fund', label: 'Education Fund', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-business-expansion', label: 'Business Expansion', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-debt-reduction', label: 'Debt Reduction', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-retirement-fund', label: 'Retirement Fund', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-investment-growth', label: 'Investment Growth', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-travel-fund', label: 'Travel Fund', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-wealth-accumulation', label: 'Wealth Accumulation', section: 'financial-goals', category: 'E. Financial Goals' },
  { id: 'goal-financial-independence', label: 'Financial Independence', section: 'financial-goals', category: 'E. Financial Goals' },

  { id: 'insurance-life', label: 'Life Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-health', label: 'Health Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-hmo', label: 'HMO', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-critical-illness', label: 'Critical Illness Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-accident', label: 'Accident Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-disability', label: 'Disability Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-property', label: 'Property Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-vehicle', label: 'Vehicle Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },
  { id: 'insurance-business', label: 'Business Insurance', section: 'insurance-coverage', category: 'F. Insurance Coverage' },

  { id: 'ai-net-worth', label: 'Net Worth', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-liquid-net-worth', label: 'Liquid Net Worth', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-monthly-cash-flow', label: 'Monthly Cash Flow', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-savings-rate', label: 'Savings Rate', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-dti', label: 'Debt-to-Income Ratio', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-dta', label: 'Debt-to-Asset Ratio', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-emergency-fund-months', label: 'Emergency Fund Months', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-credit-health', label: 'Credit Health', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-investment-readiness', label: 'Investment Readiness', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-retirement-readiness', label: 'Retirement Readiness', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-financial-independence-index', label: 'Financial Independence Index', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
  { id: 'ai-overall-financial-wellness', label: 'Overall Financial Wellness Rating', section: 'ai-analysis', category: 'G. FILSCORE AI Analysis', autoGenerated: true },
];

function toSafeNumber(rawValue: string | number | undefined) {
  const parsed = Number(rawValue);
  if (!Number.isFinite(parsed) || parsed < 0) {
    return 0;
  }
  return parsed;
}

function isBlank(rawValue: string | undefined) {
  return (rawValue ?? '').trim() === '';
}

function formatPercentInput(value: number) {
  if (!Number.isFinite(value) || value <= 0) {
    return '';
  }

  return value.toFixed(2).replace(/\.00$/, '');
}

function getSectionLabel(section: StatementSection) {
  if (section === 'assets') {
    return 'A. Assets';
  }
  if (section === 'liabilities') {
    return 'B. Liabilities';
  }
  if (section === 'monthly-income') {
    return 'C. Monthly Income';
  }
  if (section === 'monthly-expenses') {
    return 'D. Monthly Expenses';
  }
  if (section === 'financial-goals') {
    return 'E. Financial Goals';
  }
  if (section === 'insurance-coverage') {
    return 'F. Insurance Coverage';
  }
  return 'G. FILSCORE AI Analysis';
}

function buildVarianceExplanation(section: StatementSection, variance: number) {
  if (variance === 0) {
    return 'On target versus setup';
  }

  if (section === 'liabilities' || section === 'monthly-expenses') {
    return variance > 0
      ? 'Liability increased above setup and needs control'
      : 'Liability is lower than setup and improves net worth';
  }

  return variance > 0
    ? 'Value improved above setup and supports net worth'
    : 'Value declined below setup and weakens net worth';
}

export default function NetWorthPositioningPage() {
  const { applications, error, lastUpdated, loading, reload } = useLoanApplicationsMetrics();
  const snapshot = useMemo(
    () => buildNetWorthPositioningSnapshot(applications),
    [applications],
  );

  const [step, setStep] = useState<WorkflowStep>(1);
  const [asOfDate, setAsOfDate] = useState('');
  const [currency, setCurrency] = useState('PHP');
  const [selectedFinancialGoal, setSelectedFinancialGoal] = useState('');

  const [amounts, setAmounts] = useState<Record<string, string>>({});
  const [monthlyExpenseAllocationDraft, setMonthlyExpenseAllocationDraft] = useState<Record<string, string>>({});
  const [savedSetup, setSavedSetup] = useState<SavedLine[]>([]);
  const [actualEntries, setActualEntries] = useState<Record<string, string>>({});
  const [varianceNotes, setVarianceNotes] = useState<Record<string, string>>({});
  const [setupStatusMessage, setSetupStatusMessage] = useState('');
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [draftRevision, setDraftRevision] = useState<number | null>(null);

  const autosaveValue = useMemo<NetWorthPositioningDraft>(() => ({
    step,
    asOfDate,
    currency,
    selectedFinancialGoal,
    amounts,
    monthlyExpenseAllocationDraft,
    savedSetup,
    actualEntries,
    varianceNotes,
  }), [
    actualEntries,
    asOfDate,
    amounts,
    currency,
    monthlyExpenseAllocationDraft,
    selectedFinancialGoal,
    savedSetup,
    step,
    varianceNotes,
  ]);

  const handleAutosaveHydrate = useCallback((draft: NetWorthPositioningDraft) => {
    setStep(draft.step ?? 1);
    setAsOfDate(draft.asOfDate);
    setCurrency(draft.currency ?? draft.currencyCode ?? 'PHP');
    setSelectedFinancialGoal(draft.selectedFinancialGoal ?? '');
    setAmounts(draft.amounts ?? {});
    setMonthlyExpenseAllocationDraft(draft.monthlyExpenseAllocationDraft ?? {});
    setSavedSetup(draft.savedSetup ?? []);
    setActualEntries(draft.actualEntries ?? {});
    setVarianceNotes(draft.varianceNotes ?? {});
  }, []);

  useEffect(() => {
    let disposed = false;

    const loadDraft = async () => {
      try {
        const remoteDraft = await fetchAutosaveDraft<NetWorthPositioningDraft>('net-worth-positioning', 'primary');
        if (disposed || !remoteDraft) {
          return;
        }

        setDraftRevision(remoteDraft.revision);
        handleAutosaveHydrate({
          ...DEFAULT_NET_WORTH_POSITIONING_DRAFT,
          ...remoteDraft.payload,
        });
        setSetupStatusMessage(`Draft loaded (${new Date(remoteDraft.updatedAt).toLocaleString()}).`);
      } catch {
        if (!disposed) {
          setSetupStatusMessage('Unable to load saved draft right now.');
        }
      }
    };

    void loadDraft();

    return () => {
      disposed = true;
    };
  }, [handleAutosaveHydrate]);

  const handleSaveDraft = useCallback(async () => {
    setIsSavingDraft(true);
    try {
      const savedDraft = await saveAutosaveDraftRemote('net-worth-positioning', 'primary', {
        payload: autosaveValue,
        expectedRevision: draftRevision,
      });

      setDraftRevision(savedDraft.revision);
      setSetupStatusMessage(`Draft saved (${new Date(savedDraft.updatedAt).toLocaleString()}).`);
    } catch (error) {
      if (isAutosaveConflictError(error) && error.currentDraft) {
        setDraftRevision(error.currentDraft.revision);
        setSetupStatusMessage('Save conflict detected. A newer draft exists in another session. Save again to overwrite.');
      } else {
        setSetupStatusMessage('Unable to save draft right now. Please try again.');
      }
    } finally {
      setIsSavingDraft(false);
    }
  }, [autosaveValue, draftRevision]);

  const selectedCurrencyLabel = useMemo(
    () => CURRENCY_OPTIONS.find((option) => option.code === currency)?.label ?? currency,
    [currency],
  );

  const formatCurrency = useCallback((value: number) =>
    new Intl.NumberFormat('en', {
      style: 'currency',
      currency,
      useGrouping: true,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(value), [currency]);

  const formatSignedCurrency = useCallback((value: number) => {
    const absoluteAmount = formatCurrency(Math.abs(value));
    if (value > 0) {
      return `+${absoluteAmount}`;
    }
    if (value < 0) {
      return `-${absoluteAmount}`;
    }
    return absoluteAmount;
  }, [formatCurrency]);

  const workflowSteps: Array<{ id: WorkflowStep; label: string; description: string }> = [
    {
      id: 1,
      label: 'Set As Of Date',
      description: 'Set the statement reference date.',
    },
    {
      id: 2,
      label: 'Set Up Baseline',
      description: 'Enter setup values before saving.',
    },
    {
      id: 3,
      label: 'Actual vs Setup Variance',
      description: 'Enter actual values and review variance.',
    },
  ];

  const currentStepLabel = workflowSteps.find((item) => item.id === step)?.label ?? 'Net Worth Workflow';
  const completionPercent = Math.round((step / workflowSteps.length) * 100);
  const stepperButtonClass = 'loan-stepper-button';

  const setupRows = useMemo(
    () =>
      NET_WORTH_STATEMENT_ENTRIES.map((entry) => {
        const raw = amounts[entry.id] ?? '';
        return {
          ...entry,
          raw,
          amount: toSafeNumber(raw),
        };
      }),
    [amounts],
  );

  const monthlyExpenseRows = useMemo(
    () => setupRows.filter((row) => row.section === 'monthly-expenses' && !row.autoGenerated),
    [setupRows],
  );

  const monthlyExpenseTotal = useMemo(
    () => monthlyExpenseRows.reduce((sum, row) => sum + row.amount, 0),
    [monthlyExpenseRows],
  );

  const monthlyExpenseAllocationSummary = useMemo(() => {
    const totalAllocation = monthlyExpenseRows.reduce((sum, row) => {
      return sum + toSafeNumber(monthlyExpenseAllocationDraft[row.id] ?? '');
    }, 0);
    const varianceToTarget = Number((100 - totalAllocation).toFixed(2));
    const hasExpenseAmounts = monthlyExpenseRows.some((row) => row.amount > 0);

    return {
      totalAllocation: Number(totalAllocation.toFixed(2)),
      varianceToTarget,
      hasExpenseAmounts,
      isBalanced: !hasExpenseAmounts || Math.abs(varianceToTarget) < 0.01,
    };
  }, [monthlyExpenseAllocationDraft, monthlyExpenseRows]);

  useEffect(() => {
    if (monthlyExpenseRows.length === 0) {
      if (Object.keys(monthlyExpenseAllocationDraft).length > 0) {
        setMonthlyExpenseAllocationDraft({});
      }
      return;
    }

    const nextDraft = monthlyExpenseRows.reduce<Record<string, string>>((accumulator, row) => {
      const existingValue = monthlyExpenseAllocationDraft[row.id];
      if (existingValue !== undefined) {
        accumulator[row.id] = existingValue;
        return accumulator;
      }

      const share = monthlyExpenseTotal > 0 ? (row.amount / monthlyExpenseTotal) * 100 : 0;
      accumulator[row.id] = formatPercentInput(share);
      return accumulator;
    }, {});

    const changed = monthlyExpenseRows.length !== Object.keys(monthlyExpenseAllocationDraft).length
      || monthlyExpenseRows.some((row) => monthlyExpenseAllocationDraft[row.id] !== nextDraft[row.id]);

    if (changed) {
      setMonthlyExpenseAllocationDraft(nextDraft);
    }
  }, [monthlyExpenseAllocationDraft, monthlyExpenseRows, monthlyExpenseTotal]);

  const setupAssetsTotal = useMemo(
    () => setupRows.filter((row) => row.section === 'assets').reduce((sum, row) => sum + row.amount, 0),
    [setupRows],
  );
  const setupLiabilitiesTotal = useMemo(
    () => setupRows.filter((row) => row.section === 'liabilities').reduce((sum, row) => sum + row.amount, 0),
    [setupRows],
  );
  const setupNetWorth = setupAssetsTotal - setupLiabilitiesTotal;

  const stepCompletionById = useMemo<Record<WorkflowStep, number>>(() => {
    const clamp = (value: number) => Math.max(0, Math.min(100, Math.round(value)));

    const step1Checks = [
      !isBlank(asOfDate),
      !isBlank(selectedFinancialGoal),
      !isBlank(currency),
    ].filter(Boolean).length;
    const step1Percent = clamp((step1Checks / 3) * 100);

    const editableSetupRows = setupRows.filter((row) => !row.autoGenerated);
    const enteredSetupRatio = editableSetupRows.length > 0
      ? editableSetupRows.filter((row) => !isBlank(amounts[row.id])).length / editableSetupRows.length
      : 0;
    const allocationReady = !monthlyExpenseAllocationSummary.hasExpenseAmounts || monthlyExpenseAllocationSummary.isBalanced;
    const setupSaved = savedSetup.length > 0;
    const step2Percent = setupSaved
      ? 100
      : clamp(((enteredSetupRatio * 0.65) + (allocationReady ? 0.15 : 0) + (setupSaved ? 0.2 : 0)) * 100);

    const setupCount = savedSetup.length;
    const actualCompleted = setupCount > 0
      ? savedSetup.filter((line) => !isBlank(actualEntries[line.id])).length / setupCount
      : 0;
    const notesCompleted = setupCount > 0
      ? savedSetup.filter((line) => !isBlank(varianceNotes[line.id])).length / setupCount
      : 0;
    const step3Percent = setupCount === 0
      ? 0
      : clamp(((actualCompleted * 0.8) + (notesCompleted * 0.2)) * 100);

    return {
      1: step1Percent,
      2: step2Percent,
      3: step3Percent,
    };
  }, [
    actualEntries,
    amounts,
    asOfDate,
    currency,
    monthlyExpenseAllocationSummary.hasExpenseAmounts,
    monthlyExpenseAllocationSummary.isBalanced,
    savedSetup,
    selectedFinancialGoal,
    setupRows,
    varianceNotes,
  ]);

  const handleNormalizeMonthlyExpenseAllocation = () => {
    const currentTotal = monthlyExpenseRows.reduce((sum, row) => {
      return sum + toSafeNumber(monthlyExpenseAllocationDraft[row.id] ?? '');
    }, 0);

    if (currentTotal <= 0) {
      setSetupStatusMessage('Enter monthly expense allocation percentages first before normalizing to 100%.');
      return;
    }

    let runningTotal = 0;
    const normalizedDraft = monthlyExpenseRows.reduce<Record<string, string>>((accumulator, row, index) => {
      if (index === monthlyExpenseRows.length - 1) {
        accumulator[row.id] = formatPercentInput(Math.max(0, 100 - runningTotal));
        return accumulator;
      }

      const nextValue = Number(((toSafeNumber(monthlyExpenseAllocationDraft[row.id] ?? '') / currentTotal) * 100).toFixed(2));
      runningTotal += nextValue;
      accumulator[row.id] = formatPercentInput(nextValue);
      return accumulator;
    }, {});

    setMonthlyExpenseAllocationDraft(normalizedDraft);
    setSetupStatusMessage('Monthly expense allocation percentages were normalized to 100%.');
  };

  const handleApplyMonthlyExpenseAllocation = () => {
    if (!monthlyExpenseAllocationSummary.isBalanced) {
      setSetupStatusMessage(`Monthly expense allocation must total 100%. Current variance is ${monthlyExpenseAllocationSummary.varianceToTarget.toFixed(2)}%.`);
      return;
    }

    if (monthlyExpenseTotal <= 0) {
      setSetupStatusMessage('Enter monthly expense setup amounts first before applying revised allocation percentages.');
      return;
    }

    let allocatedTotal = 0;
    setAmounts((previous) => {
      const next = { ...previous };

      monthlyExpenseRows.forEach((row, index) => {
        if (index === monthlyExpenseRows.length - 1) {
          next[row.id] = (monthlyExpenseTotal - allocatedTotal).toFixed(2);
          return;
        }

        const nextAmount = Number(((monthlyExpenseTotal * toSafeNumber(monthlyExpenseAllocationDraft[row.id] ?? '')) / 100).toFixed(2));
        allocatedTotal += nextAmount;
        next[row.id] = nextAmount.toFixed(2);
      });

      return next;
    });

    setSetupStatusMessage('Monthly expense setup amounts were recalculated using the revised allocation percentages.');
  };

  const handleSaveSetup = () => {
    if (!asOfDate) {
      setSetupStatusMessage('Please set As Of date before saving this net worth setup.');
      setStep(1);
      return;
    }

    if (!monthlyExpenseAllocationSummary.isBalanced) {
      setSetupStatusMessage(`Monthly expense allocation must stay at 100% before saving Step 2. Current variance is ${monthlyExpenseAllocationSummary.varianceToTarget.toFixed(2)}%.`);
      return;
    }

    const setupLines = setupRows
      .filter((row) => !row.autoGenerated && row.amount > 0)
      .map((row) => ({
        id: row.id,
        label: row.label,
        section: row.section,
        category: row.category,
        setupAmount: row.amount,
      }));

    if (setupLines.length === 0) {
      setSetupStatusMessage('Please enter at least one balance sheet amount before saving setup.');
      setStep(1);
      return;
    }

    setSavedSetup(setupLines);
    setActualEntries({});
    setVarianceNotes({});
    setSetupStatusMessage('Setup saved. Continue with Step 3 to enter actual values and monitor variance.');
    setStep(3);
  };

  const varianceRows = useMemo(() => {
    return savedSetup.map((line) => {
      const rawActual = actualEntries[line.id] ?? '';
      const hasActual = !isBlank(rawActual);
      const actualAmount = hasActual ? toSafeNumber(rawActual) : 0;
      const variance = hasActual ? actualAmount - line.setupAmount : 0;

      return {
        ...line,
        hasActual,
        actualAmount,
        variance,
      };
    });
  }, [savedSetup, actualEntries]);

  const totals = useMemo(() => {
    const setupAssets = varianceRows
      .filter((row) => row.section === 'assets')
      .reduce((sum, row) => sum + row.setupAmount, 0);
    const setupLiabilities = varianceRows
      .filter((row) => row.section === 'liabilities')
      .reduce((sum, row) => sum + row.setupAmount, 0);

    const actualAssets = varianceRows
      .filter((row) => row.section === 'assets' && row.hasActual)
      .reduce((sum, row) => sum + row.actualAmount, 0);
    const actualLiabilities = varianceRows
      .filter((row) => row.section === 'liabilities' && row.hasActual)
      .reduce((sum, row) => sum + row.actualAmount, 0);

    return {
      setupAssets,
      setupLiabilities,
      setupNetWorth: setupAssets - setupLiabilities,
      actualAssets,
      actualLiabilities,
      actualNetWorth: actualAssets - actualLiabilities,
    };
  }, [varianceRows]);

  const topVarianceRows = useMemo(() => {
    return varianceRows
      .filter((row) => row.hasActual)
      .map((row) => ({
        ...row,
        magnitude: Math.abs(row.variance),
      }))
      .sort((left, right) => right.magnitude - left.magnitude)
      .slice(0, 5);
  }, [varianceRows]);

  const maxVarianceMagnitude = useMemo(
    () => topVarianceRows.reduce((largest, row) => Math.max(largest, row.magnitude), 0),
    [topVarianceRows],
  );

  const aiRecommendations = useMemo(() => {
    if (!varianceRows.length) {
      return ['Save setup first so recommendations can be generated.'];
    }

    const hasAnyActual = varianceRows.some((row) => row.hasActual);
    if (!hasAnyActual) {
      return ['Enter actual values in Step 3 to unlock AI recommendations for net worth variance.'];
    }

    const prioritized = varianceRows
      .filter((row) => row.hasActual)
      .map((row) => {
        const riskMagnitude = row.section === 'liabilities' || row.section === 'monthly-expenses'
          ? Math.max(row.variance, 0)
          : Math.max(-row.variance, 0);
        return {
          ...row,
          riskMagnitude,
        };
      })
      .sort((left, right) => right.riskMagnitude - left.riskMagnitude)
      .slice(0, 3)
      .filter((row) => row.riskMagnitude > 0);

    const recommendations = prioritized.map((row) => {
      if (row.section === 'liabilities') {
        return `${row.label} is above setup by ${formatCurrency(row.variance)}. Prioritize payoff sequencing to protect net worth.`;
      }
      return `${row.label} is below setup by ${formatCurrency(Math.abs(row.variance))}. Rebuild this value area to stabilize net worth.`;
    });

    if (recommendations.length === 0) {
      recommendations.push('Actual values are aligned with setup. Keep updating variance explanations to maintain tracking quality.');
    }

    recommendations.push(`Net worth projection is ${formatSignedCurrency(totals.actualNetWorth || totals.setupNetWorth)} using current entries.`);

    return recommendations.slice(0, 4);
  }, [formatCurrency, formatSignedCurrency, varianceRows, totals.actualNetWorth, totals.setupNetWorth]);

  return (
    <div className="psychometric-page networth-dashboard-page">
      <section className="psychometric-hero networth-dashboard-hero">
        <div className="psychometric-hero-copy">
          <span className="psychometric-eyebrow">Net Worth Workflow Controls</span>
          <h1>Net Worth  and Goal Tracking</h1>
          <p>
            Period:  <strong>{snapshot.dateLabel}</strong>
          </p>
          <p>
            Navigate a guided net-worth workflow to set period coverage, build setup amounts, then compare
            actual values and track variances with AI guidance.
          </p>
        </div>

        <div className="psychometric-hero-metric networth-dashboard-scorecard">
          <span>Net Worth Position Score</span>
          <strong>{snapshot.healthScore.toFixed(1)}</strong>
          <small>{`Step ${step}/${workflowSteps.length}: ${currentStepLabel}`}</small>
        </div>
      </section>

      <section className="psychometric-panel">
        <div className="psychometric-panel-header">
          <div>
            <span className="psychometric-panel-kicker"></span>
            <h2>Four Steps in Setting Up Net Worth and Goal Tracking</h2>
          </div>
        </div>
        <p className="psychometric-section-note">
          
        </p>
        
      </section>

            <section className="psychometric-summary-grid budget-dashboard-summary-grid">
        <article className="psychometric-summary-card psychometric-summary-card-highlight">
          <span>What do you own and what do you owe?</span>
          <strong>Build Your Net Worth</strong>
          <small>Record All Assets. Record All Liabilities.Calculate Net Worth</small>
        </article>

        <article className="psychometric-summary-card">
          <span>Where do you want to be?</span>
          <strong>Set Your Financial Goals</strong>
          <small>Create Financial Goals.  Assign Priorities. Set target amounts and dealine.</small>
        </article>

        <article className="psychometric-summary-card">
          <span>How will you achieve your goals?</span>
          <strong>Create Your Financial Action Plan</strong>
          <small>Determine monthly goal  for savings and investment plan. Create strategies.</small>
        </article>

        <article className="psychometric-summary-card">
          <span>Are you getting closer to your goals?</span>
          <strong>Monitor Progress</strong>
          <small>Track progress. Get insights to continuously improve.</small>
        </article>
      </section>

      <section className="psychometric-panel">
        <div className="psychometric-panel-header">
          <div>
            <span className="psychometric-panel-kicker">Global Comparator</span>
            <h2>Your Income and Wealth Standing in the World.   </h2>
          </div>
        </div>
        <p className="psychometric-section-note">
          Compare your income and wealth standing globally using the World Inequality Database comparator. 
        </p>
        <a
          href="https://wid.world/income-comparator/"
          target="_blank"
          rel="noreferrer"
          className="auth-link-button"
        >
          Open WID Income Comparator
        </a>
      </section>

      <section className="psychometric-panel">
        <div className="psychometric-panel-header">
          <div>
            <span className="psychometric-panel-kicker"></span>
            <h2>Let's do the work. Follow the workflow</h2>
          </div>
        </div>
        <p className="psychometric-section-note">
          
        </p>
        
      </section>
      <section className="psychometric-summary-grid budget-dashboard-summary-grid">
        <article className="psychometric-summary-card psychometric-summary-card-highlight">
          <span>Progress</span>
          <strong>{completionPercent}%</strong>
          <small>{currentStepLabel}</small>
        </article>

        <article className="psychometric-summary-card">
          <span>Setup Assets</span>
          <strong>{formatCurrency(setupAssetsTotal)}</strong>
          <small>Current setup for asset lines</small>
        </article>

        <article className="psychometric-summary-card">
          <span>Setup Liabilities</span>
          <strong>{formatCurrency(setupLiabilitiesTotal)}</strong>
          <small>Current setup for liability lines</small>
        </article>

        <article className="psychometric-summary-card">
          <span>Setup Net Worth</span>
          <strong>{formatSignedCurrency(setupNetWorth)}</strong>
          <small>{snapshot.performanceBand}</small>
        </article>
      </section>

      <section className="budget-dashboard-layout">
        <div className="budget-dashboard-main">
          <article className="psychometric-panel">
            <div className="psychometric-panel-header">
              <div>
                <span className="psychometric-panel-kicker">Workflow Form</span>
                <h2>{`Step ${step}: ${currentStepLabel}`}</h2>
              </div>
              <div className="budget-workflow-inline-actions">
                <button
                  type="button"
                  className="psychometric-reset-button"
                  onClick={handleSaveDraft}
                  disabled={isSavingDraft}
                >
                  {isSavingDraft ? 'Saving...' : 'Save All Steps'}
                </button>
                <button
                  type="button"
                  className="psychometric-reset-button"
                  onClick={reload}
                  disabled={loading}
                >
                  {loading ? 'Refreshing...' : 'Refresh Data'}
                </button>
              </div>
            </div>

            {error ? (
              <p className="psychometric-section-note" role="alert">
                {error}
              </p>
            ) : null}

            <p className="psychometric-section-note">
              {snapshot.sourceLabel} | {snapshot.sourceApplicationNo}
              {lastUpdated ? ` | Updated ${lastUpdated.toLocaleString()}` : ''}
            </p>

            {setupStatusMessage ? (
              <div className="budget-workflow-status-banner" role="status">
                {setupStatusMessage}
              </div>
            ) : null}

            {step === 1 ? (
              <div className="budget-workflow-step-block">
                <h3 className="workflow-duplicate-step-title">Step 1: Set As Of Date</h3>
                <p className="psychometric-section-note">
                  FILSCORE Personal Net Worth Statement. Set As Of date, then encode values for suggested accounts.
                </p>

                <div className="budget-dashboard-category-summary" style={{ marginBottom: '8px' }}>
                  <div className="budget-dashboard-category-summary-card">
                    <span>FILSCORE</span>
                    <strong>Personal Net Worth Statement</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Suggested Accounts</span>
                    <strong>A to G Sections</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Financial Goals</span>
                    <select
                      value={selectedFinancialGoal}
                      onChange={(event) => setSelectedFinancialGoal(event.target.value)}
                      className="budget-dashboard-category-input"
                      aria-label="Financial goals"
                    >
                      <option value="">Select financial goal</option>
                      {FINANCIAL_GOAL_OPTIONS.map((goal) => (
                        <option key={goal} value={goal}>
                          {goal}
                        </option>
                      ))}
                    </select>
                     <div className="budget-dashboard-category-summary-card">
                    <span>Suggested Accounts</span>
                    <strong>A to G Sections</strong>
                  </div>
                  </div>
                </div>

                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', marginBottom: '8px' }}>
                  <label>
                    As Of
                    <input
                      type="date"
                      value={asOfDate}
                      onChange={(event) => setAsOfDate(event.target.value)}
                    />
                  </label>

                  <label>
                    Currency
                    <select
                      value={currency}
                      onChange={(event) => setCurrency(event.target.value)}
                      className="budget-dashboard-category-input"
                      aria-label="Statement currency"
                    >
                      {CURRENCY_OPTIONS.map((option) => (
                        <option key={option.code} value={option.code}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  </label>
                </div>

                <div className="psychometric-scale-table-wrap">
                  <table className="psychometric-scale-table">
                      <colgroup>
                      <col style={{ width: '15%' }} />   {/* Statement Section */}
                      <col style={{ width: '25%' }} />   {/* Suggested Account Group */}
                      <col style={{ width: '25%' }} />   {/* Line Item */}
                      <col style={{ width: '25%' }} />   {/* Setup Amount */}
                      <col style={{ width: '10%' }} />   {/* Remarks */}
                       </colgroup>

                    <thead>
                      <tr>
                        <th>Statement Section</th>
                        <th>Suggested Account Group</th>
                        <th>Line Item</th>
                        <th>Setup Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                      {setupRows.map((row) => (
                        <tr key={row.id}>
                          <td data-label="Statement Section">{getSectionLabel(row.section)}</td>
                          <td data-label="Suggested Account Group">{row.category}</td>
                          <td data-label="Line Item">{row.label}</td>
                          <td data-label="Setup Amount">
                            {row.autoGenerated ? (
                              <span className="psychometric-section-note">Automatically Generated</span>
                            ) : (
                              <input
                                type="number"
                                min={0}
                                step="0.01"
                                value={row.raw}
                                onChange={(event) => {
                                  setAmounts((previous) => ({
                                    ...previous,
                                    [row.id]: event.target.value,
                                  }));
                                }}
                                className="budget-dashboard-category-input"
                                placeholder="0"
                                aria-label={`${row.label} setup amount`}
                              />
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <div className="budget-workflow-inline-actions">
                  <button type="button" className="budget-dashboard-category-reset" onClick={handleSaveDraft} disabled={isSavingDraft}>
                    {isSavingDraft ? 'Saving...' : 'Save'}
                  </button>
                  <button type="button" className="psychometric-reset-button" onClick={() => setStep(2)}>
                    Continue to Step 2
                  </button>
                </div>
              </div>
            ) : null}

            {step === 2 ? (
              <div className="budget-workflow-step-block">
                <h3 className="workflow-duplicate-step-title">Step 2: Set Up Baseline</h3>
                <p className="psychometric-section-note">
                  Review setup values, then click save setup so lines appear in Step 3 first column.
                </p>

                <div className="budget-dashboard-category-summary">
                  <div className="budget-dashboard-category-summary-card">
                    <span>As Of</span>
                    <strong>{asOfDate || 'Not set'}</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Financial Goal</span>
                    <strong>{selectedFinancialGoal || 'Not selected'}</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Setup Entries</span>
                    <strong>{setupRows.filter((row) => !row.autoGenerated && row.amount > 0).length}</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Setup Net Worth</span>
                    <strong>{formatSignedCurrency(setupNetWorth)}</strong>
                  </div>
                </div>

                <div className="budget-dashboard-category-summary">
                  <div className="budget-dashboard-category-summary-card">
                    <span>Monthly Expense Total</span>
                    <strong>{formatCurrency(monthlyExpenseTotal)}</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Expense Allocation Total</span>
                    <strong>{monthlyExpenseAllocationSummary.totalAllocation.toFixed(2)}%</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Variance to 100%</span>
                    <strong>{monthlyExpenseAllocationSummary.varianceToTarget.toFixed(2)}%</strong>
                  </div>
                  <div className="budget-dashboard-category-summary-card">
                    <span>Status</span>
                    <strong>{monthlyExpenseAllocationSummary.isBalanced ? 'Balanced' : 'Needs Reconciliation'}</strong>
                  </div>
                </div>

                <p className="psychometric-section-note">
                  Monthly expense lines can now be revised by allocation percentage. Keep the expense allocation at 100% before saving this baseline.
                </p>

                <div className="psychometric-scale-table-wrap">
                  <table className="psychometric-scale-table">
                    <thead>
                      <tr>
                        <th>Expense Category</th>
                        <th>Setup Amount</th>
                        <th>Allocation %</th>
                      </tr>
                    </thead>
                    <tbody>
                      {monthlyExpenseRows.filter((row) => row.amount > 0).map((row) => (
                        <tr key={row.id}>
                          <td data-label="Expense Category">{row.label}</td>
                          <td data-label="Setup Amount">{formatCurrency(row.amount)}</td>
                          <td data-label="Allocation %">
                            <input
                              type="number"
                              min={0}
                              max={100}
                              step="0.01"
                              value={monthlyExpenseAllocationDraft[row.id] ?? ''}
                              onChange={(event) => {
                                setMonthlyExpenseAllocationDraft((previous) => ({
                                  ...previous,
                                  [row.id]: event.target.value,
                                }));
                              }}
                              className="budget-dashboard-category-input"
                              aria-label={`${row.label} allocation percentage`}
                            />
                          </td>
                        </tr>
                      ))}
                      {monthlyExpenseRows.filter((row) => row.amount > 0).length === 0 ? (
                        <tr>
                          <td colSpan={3}>No monthly expense setup lines yet. Return to Step 1 and add values.</td>
                        </tr>
                      ) : null}
                    </tbody>
                  </table>
                </div>

                <div className="psychometric-scale-table-wrap">
                  <table className="psychometric-scale-table">
                    <thead>
                      <tr>
                        <th>Statement Section</th>
                        <th>Suggested Account Group</th>
                        <th>Line Item</th>
                        <th>Setup Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                      {setupRows
                        .filter((row) => !row.autoGenerated && row.amount > 0)
                        .map((row) => (
                          <tr key={row.id}>
                            <td data-label="Statement Section">{getSectionLabel(row.section)}</td>
                            <td data-label="Suggested Account Group">{row.category}</td>
                            <td data-label="Line Item">{row.label}</td>
                            <td data-label="Setup Amount">{formatCurrency(row.amount)}</td>
                          </tr>
                        ))}
                      {setupRows.filter((row) => !row.autoGenerated && row.amount > 0).length === 0 ? (
                        <tr>
                          <td colSpan={4}>No setup lines yet. Return to Step 1 and add values.</td>
                        </tr>
                      ) : null}
                    </tbody>
                  </table>
                </div>

                <div className="budget-workflow-inline-actions">
                  <button type="button" className="budget-dashboard-category-reset" onClick={handleSaveDraft} disabled={isSavingDraft}>
                    {isSavingDraft ? 'Saving...' : 'Save'}
                  </button>
                  <button type="button" className="budget-dashboard-category-reset" onClick={() => setStep(1)}>
                    Back to Step 1
                  </button>
                  <button type="button" className="budget-dashboard-category-reset" onClick={handleNormalizeMonthlyExpenseAllocation}>
                    Normalize to 100%
                  </button>
                  <button type="button" className="budget-dashboard-category-reset" onClick={handleApplyMonthlyExpenseAllocation}>
                    Apply Revised % Allocation
                  </button>
                  <button type="button" className="psychometric-reset-button" onClick={handleSaveSetup}>
                    Save Setup and Continue to Step 3
                  </button>
                </div>
              </div>
            ) : null}

            {step === 3 ? (
              <div className="budget-workflow-step-block">
                <h3 className="workflow-duplicate-step-title">Step 3: Actual vs Setup Variance</h3>
                <p className="psychometric-section-note">
                  First column shows saved setup. Second column is blank for actual entry. Third column is variance.
                  Fourth column shows variance explanation in small letters.
                </p>

                {savedSetup.length === 0 ? (
                  <p className="psychometric-section-note">
                    No saved setup yet. Complete Step 2 and click save setup first.
                  </p>
                ) : (
                  <div className="psychometric-scale-table-wrap">
                    <table className="psychometric-scale-table">
                      <thead>
                        <tr>
                          <th>Setup (Saved)</th>
                          <th>Actual (User Input)</th>
                          <th>Variance</th>
                          <th>Variance Explanation</th>
                        </tr>
                      </thead>
                      <tbody>
                        {varianceRows.map((row) => (
                          <tr key={row.id}>
                            <td data-label="Setup (Saved)">
                              <strong>{row.label}</strong>
                              <div>{getSectionLabel(row.section)}</div>
                              <div>{row.category}</div>
                              <div>{formatCurrency(row.setupAmount)}</div>
                            </td>
                            <td data-label="Actual (User Input)">
                              <input
                                type="number"
                                min={0}
                                step="0.01"
                                value={actualEntries[row.id] ?? ''}
                                onChange={(event) => {
                                  setActualEntries((previous) => ({
                                    ...previous,
                                    [row.id]: event.target.value,
                                  }));
                                }}
                                placeholder="Enter actual value"
                                aria-label={`${row.label} actual value`}
                              />
                            </td>
                            <td data-label="Variance">
                              {row.hasActual ? formatSignedCurrency(row.variance) : 'Pending input'}
                            </td>
                            <td data-label="Variance Explanation">
                              <small className="budget-workflow-variance-copy">
                                {row.hasActual
                                  ? (varianceNotes[row.id]?.trim() || buildVarianceExplanation(row.section, row.variance))
                                  : 'Awaiting actual value from user.'}
                              </small>
                              {row.hasActual ? (
                                <input
                                  type="text"
                                  value={varianceNotes[row.id] ?? ''}
                                  onChange={(event) => {
                                    setVarianceNotes((previous) => ({
                                      ...previous,
                                      [row.id]: event.target.value,
                                    }));
                                  }}
                                  placeholder="Optional explanation"
                                  aria-label={`${row.label} variance explanation`}
                                />
                              ) : null}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                <div className="budget-workflow-inline-actions">
                  <button type="button" className="budget-dashboard-category-reset" onClick={handleSaveDraft} disabled={isSavingDraft}>
                    {isSavingDraft ? 'Saving...' : 'Save'}
                  </button>
                  <button type="button" className="budget-dashboard-category-reset" onClick={() => setStep(2)}>
                    Back to Step 2
                  </button>
                </div>
              </div>
            ) : null}
          </article>

          {step === 3 ? (
            <article className="psychometric-panel">
              <div className="psychometric-panel-header">
                <div>
                  <span className="psychometric-panel-kicker">AI Recommendations and Graphs</span>
                  <h2>Net worth variance coaching and visuals</h2>
                </div>
              </div>

              <div className="budget-workflow-ai-grid">
                <article className="budget-workflow-ai-card">
                  <h3>AI Recommendations</h3>
                  <ul className="psychometric-breakdown-list">
                    {aiRecommendations.map((item) => (
                      <li key={item}>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </article>

                <article className="budget-workflow-ai-card">
                  <h3>Setup vs Actual Net Worth Graph</h3>
                  <div className="budget-workflow-graph-row">
                    <span>Setup Net Worth</span>
                    <div className="budget-workflow-graph-track">
                      <div
                        className="budget-workflow-graph-bar budget-workflow-graph-bar-setup"
                        style={{
                          width: `${Math.min(
                            100,
                            Math.abs(totals.setupNetWorth) > 0
                              ? (Math.abs(totals.setupNetWorth) / Math.max(Math.abs(totals.setupNetWorth), Math.abs(totals.actualNetWorth), 1)) * 100
                              : 0,
                          )}%`,
                        }}
                      />
                    </div>
                    <strong>{formatSignedCurrency(totals.setupNetWorth)}</strong>
                  </div>

                  <div className="budget-workflow-graph-row">
                    <span>Actual Net Worth</span>
                    <div className="budget-workflow-graph-track">
                      <div
                        className={`budget-workflow-graph-bar ${totals.actualNetWorth < totals.setupNetWorth ? 'budget-workflow-graph-bar-warning' : 'budget-workflow-graph-bar-actual'}`}
                        style={{
                          width: `${Math.min(
                            100,
                            Math.abs(totals.actualNetWorth) > 0
                              ? (Math.abs(totals.actualNetWorth) / Math.max(Math.abs(totals.setupNetWorth), Math.abs(totals.actualNetWorth), 1)) * 100
                              : 0,
                          )}%`,
                        }}
                      />
                    </div>
                    <strong>{formatSignedCurrency(totals.actualNetWorth)}</strong>
                  </div>

                  <div className="budget-workflow-graph-row">
                    <span>Net Worth Variance</span>
                    <div className="budget-workflow-graph-track">
                      <div
                        className={`budget-workflow-graph-bar ${totals.actualNetWorth - totals.setupNetWorth < 0 ? 'budget-workflow-graph-bar-alert' : 'budget-workflow-graph-bar-actual'}`}
                        style={{
                          width: `${Math.min(
                            100,
                            Math.abs(totals.actualNetWorth - totals.setupNetWorth) > 0
                              ? (Math.abs(totals.actualNetWorth - totals.setupNetWorth) / Math.max(Math.abs(totals.setupNetWorth), 1)) * 100
                              : 0,
                          )}%`,
                        }}
                      />
                    </div>
                    <strong>{formatSignedCurrency(totals.actualNetWorth - totals.setupNetWorth)}</strong>
                  </div>
                </article>

                <article className="budget-workflow-ai-card">
                  <h3>Top Variance Graph</h3>
                  {topVarianceRows.length === 0 ? (
                    <p className="psychometric-section-note">Enter actual values to visualize top variance lines.</p>
                  ) : (
                    <div className="budget-workflow-variance-chart">
                      {topVarianceRows.map((row) => (
                        <div key={row.id} className="budget-workflow-variance-row">
                          <span>{row.label}</span>
                          <div className="budget-workflow-graph-track">
                            <div
                              className={`budget-workflow-graph-bar ${row.section === 'liabilities' && row.variance > 0 ? 'budget-workflow-graph-bar-warning' : 'budget-workflow-graph-bar-setup'}`}
                              style={{
                                width: `${maxVarianceMagnitude > 0 ? (row.magnitude / maxVarianceMagnitude) * 100 : 0}%`,
                              }}
                            />
                          </div>
                          <strong>{formatSignedCurrency(row.variance)}</strong>
                        </div>
                      ))}
                    </div>
                  )}
                </article>
              </div>
            </article>
          ) : null}
        </div>

        <aside className="budget-dashboard-side">
          <article className="psychometric-panel psychometric-sticky-panel">
            <div className="psychometric-panel-header">
              <div>
                <span className="psychometric-panel-kicker">Workflow Steps</span>
                <h2>Navigate Workflow Steps</h2>
              </div>
            </div>

            <div className="lending-psychometric-step-list">
              {workflowSteps.map((workflowStep) => {
                const isActive = step === workflowStep.id;
                const isCompleted = step > workflowStep.id;
                const stepPercent = stepCompletionById[workflowStep.id];
                const statusLabel = `${stepPercent}% information provided`;

                return (
                  <button
                    key={workflowStep.id}
                    type="button"
                    onClick={() => setStep(workflowStep.id)}
                    className={`${stepperButtonClass} lending-psychometric-step-button ${isActive ? 'loan-stepper-button-active border-blue-500 bg-blue-50 text-blue-700 shadow-sm' : 'loan-stepper-button-idle border-gray-200 bg-white hover:border-blue-400 hover:text-blue-600'}`}
                  >
                    <div className={`lending-psychometric-step-index ${isActive || isCompleted ? 'bg-blue-600 text-white' : 'bg-gray-300 text-gray-600'}`}>
                      {workflowStep.id}
                    </div>
                    <div className="lending-psychometric-step-copy">
                      <strong>{workflowStep.label}</strong>
                      <span>{statusLabel}</span>
                      <div className="lending-step-information-track" aria-hidden="true">
                        <div
                          className={`lending-step-information-bar${stepPercent < 30 ? ' lending-step-information-bar-low' : ''}`}
                          style={{ width: `${stepPercent}%` }}
                        />
                      </div>
                      <small>{workflowStep.description}</small>
                    </div>
                  </button>
                );
              })}
            </div>
          </article>

          <article className="psychometric-panel psychometric-sticky-panel">
            <span className="psychometric-panel-kicker">Setup Snapshot</span>
            <h2>{savedSetup.length > 0 ? 'Saved Setup' : 'Draft Setup'}</h2>
            <ul className="psychometric-breakdown-list">
              <li>
                <span>As Of</span>
                <strong>{asOfDate || 'Not set'}</strong>
              </li>
              <li>
                <span>Currency</span>
                <strong>{selectedCurrencyLabel}</strong>
              </li>
              <li>
                <span>Financial Goal</span>
                <strong>{selectedFinancialGoal || 'Not selected'}</strong>
              </li>
              <li>
                <span>Setup Entries</span>
                <strong>{savedSetup.length || setupRows.filter((row) => !row.autoGenerated && row.amount > 0).length}</strong>
              </li>
              <li>
                <span>Setup Net Worth</span>
                <strong>{formatSignedCurrency(savedSetup.length > 0 ? totals.setupNetWorth : setupNetWorth)}</strong>
              </li>
            </ul>
          </article>

          <article className="psychometric-panel psychometric-sticky-panel">
            <span className="psychometric-panel-kicker">Position Health</span>
            <h2>{snapshot.performanceBand}</h2>
            <ul className="psychometric-breakdown-list">
              <li>
                <span>Health Score</span>
                <strong>{snapshot.healthScore.toFixed(1)}</strong>
              </li>
              <li>
                <span>Action</span>
                <strong>{snapshot.actionLabel}</strong>
              </li>
              <li>
                <span>Source</span>
                <strong>{snapshot.sourceApplicationNo || 'N/A'}</strong>
              </li>
            </ul>
          </article>
        </aside>
      </section>

      <section className="psychometric-panel">
        <div className="psychometric-panel-header">
          <div>
            <span className="psychometric-panel-kicker">Global Comparator</span>
            <h2>Your Income and Wealth Standing in the World</h2>
          </div>
        </div>
        <p className="psychometric-section-note">
          Compare your income and wealth standing globally using the World Inequality Database comparator.
        </p>
        <a
          href="https://wid.world/income-comparator/"
          target="_blank"
          rel="noreferrer"
          className="auth-link-button"
        >
          Open WID Income Comparator
        </a>
      </section>
    </div>
  );
}
