import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { Printer, RefreshCw, X } from 'lucide-react'

import { readReplicatedBuildProfile, type ReplicatedBuildProfile } from '../scoring/buildProfileReplication'
import { NET_WORTH_STATEMENT_ENTRIES, type StatementSection } from '../scoring/NetWorthPositioningPage'

import './AdminFinancialStatementPage.css'

type PaperSize = 'a4' | 'letter'

type SummaryRow = {
  category: string
  amount: number
}

const REPORT_SECTIONS: Array<{ section: StatementSection; label: string }> = [
  { section: 'assets', label: 'Assets' },
  { section: 'liabilities', label: 'Liabilities' },
  { section: 'monthly-income', label: 'Personal Income' },
  { section: 'monthly-expenses', label: 'Personal Expenses' },
]

const toAmount = (value: string | undefined) => {
  const amount = Number(value)
  return Number.isFinite(amount) && amount > 0 ? amount : 0
}

function summarizeSection(profile: ReplicatedBuildProfile | null, section: StatementSection, desired: boolean): SummaryRow[] {
  if (!profile) return []

  const totals = new Map<string, number>()
  NET_WORTH_STATEMENT_ENTRIES
    .filter((entry) => entry.section === section && !entry.autoGenerated)
    .forEach((entry) => {
      const key = desired ? `wealthActual.${entry.id}` : entry.id
      totals.set(entry.category, (totals.get(entry.category) ?? 0) + toAmount(profile.values[key]))
    })

  return [...totals.entries()]
    .map(([category, amount]) => ({ category, amount }))
    .filter((row) => row.amount > 0)
}

function recommendationFor(section: StatementSection, gap: number, label: string) {
  const needsIncrease = gap > 0
  if (section === 'liabilities') {
    return needsIncrease
      ? `Review why desired ${label.toLowerCase()} is higher and avoid unnecessary borrowing.`
      : `Direct available surplus toward reducing ${label.toLowerCase()} on schedule.`
  }
  if (section === 'monthly-expenses') {
    return needsIncrease
      ? `Validate the planned increase in ${label.toLowerCase()} against monthly cash flow.`
      : `Reduce ${label.toLowerCase()} through a defined monthly spending limit.`
  }
  if (section === 'monthly-income') {
    return needsIncrease
      ? `Set a monthly action plan to grow ${label.toLowerCase()} toward the desired amount.`
      : `Protect the current ${label.toLowerCase()} level and reassess the target.`
  }
  return needsIncrease
    ? `Prioritize regular contributions to close the ${label.toLowerCase()} gap.`
    : `Preserve the current ${label.toLowerCase()} position and review allocation quality.`
}

type FinancialStatementModalProps = {
  onClose: () => void
}

export default function FinancialStatementModal({ onClose }: FinancialStatementModalProps) {
  const [profile, setProfile] = useState(() => readReplicatedBuildProfile())
  const [paperSize, setPaperSize] = useState<PaperSize>('a4')
  const [fontSize, setFontSize] = useState(10)

  const currency = profile?.values.wealthCurrency || 'PHP'
  const money = useMemo(() => new Intl.NumberFormat('en', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0,
  }), [currency])
  const today = new Intl.DateTimeFormat('en', { dateStyle: 'long' }).format(new Date())

  useEffect(() => {
    setProfile(readReplicatedBuildProfile())
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', closeOnEscape)
    return () => document.removeEventListener('keydown', closeOnEscape)
  }, [onClose])

  const sectionRows = useMemo(() => Object.fromEntries(REPORT_SECTIONS.map(({ section }) => [
    section,
    {
      current: summarizeSection(profile, section, false),
      desired: summarizeSection(profile, section, true),
    },
  ])) as Record<StatementSection, { current: SummaryRow[]; desired: SummaryRow[] }>, [profile])

  const total = (section: StatementSection, desired: boolean) =>
    sectionRows[section][desired ? 'desired' : 'current'].reduce((sum, row) => sum + row.amount, 0)

  const currentNetWorth = total('assets', false) - total('liabilities', false)
  const desiredNetWorth = total('assets', true) - total('liabilities', true)
  const currentNetIncome = total('monthly-income', false) - total('monthly-expenses', false)
  const desiredNetIncome = total('monthly-income', true) - total('monthly-expenses', true)

  const topGaps = useMemo(() => NET_WORTH_STATEMENT_ENTRIES
    .filter((entry) => !entry.autoGenerated && REPORT_SECTIONS.some(({ section }) => section === entry.section))
    .map((entry) => {
      const current = toAmount(profile?.values[entry.id])
      const desired = toAmount(profile?.values[`wealthActual.${entry.id}`])
      return { ...entry, current, desired, gap: desired - current }
    })
    .filter((entry) => entry.gap !== 0)
    .sort((left, right) => Math.abs(right.gap) - Math.abs(left.gap))
    .slice(0, 5), [profile])

  const renderStatement = (desired: boolean) => (
    <section className="admin-statement-column">
      <header>
        <span>{desired ? 'Desired Position' : 'Current Position'}</span>
        <h2>{desired ? 'Desired Net Worth & Cash Flow' : 'Current Net Worth & Cash Flow'}</h2>
      </header>
      {REPORT_SECTIONS.map(({ section, label }) => {
        const rows = sectionRows[section][desired ? 'desired' : 'current']
        return <div className="admin-statement-section" key={section}>
          <h3>{label}</h3>
          {rows.length > 0 ? rows.map((row) => <div className="admin-statement-row" key={row.category}>
            <span>{row.category}</span><strong>{money.format(row.amount)}</strong>
          </div>) : <p className="admin-statement-empty">No amount entered</p>}
          <div className="admin-statement-total"><span>Total {label}</span><strong>{money.format(total(section, desired))}</strong></div>
        </div>
      })}
      <div className="admin-statement-key-totals">
        <div><span>Net Worth</span><strong>{money.format(desired ? desiredNetWorth : currentNetWorth)}</strong></div>
        <div><span>Net Monthly Income</span><strong>{money.format(desired ? desiredNetIncome : currentNetIncome)}</strong></div>
      </div>
    </section>
  )

  return createPortal(<div className="admin-financial-statement-overlay" role="dialog" aria-modal="true" aria-labelledby="financial-statement-title" onMouseDown={(event) => {
    if (event.target === event.currentTarget) onClose()
  }}>
    <div className="admin-financial-statement-page">
      <div className="admin-statement-toolbar" aria-label="Statement display controls">
      <label>Paper
        <select value={paperSize} onChange={(event) => setPaperSize(event.target.value as PaperSize)}>
          <option value="a4">A4</option>
          <option value="letter">Short coupon / Letter</option>
        </select>
      </label>
      <label>Font size
        <input type="range" min="8" max="14" step="1" value={fontSize} onChange={(event) => setFontSize(Number(event.target.value))} />
        <output>{fontSize} pt</output>
      </label>
      <button type="button" title="Refresh Build Profile data" onClick={() => setProfile(readReplicatedBuildProfile())}><RefreshCw aria-hidden="true" /> Refresh</button>
      <button type="button" title="Print financial statement" onClick={() => window.print()}><Printer aria-hidden="true" /> Print</button>
      <button type="button" title="Close financial statement" aria-label="Close financial statement" onClick={onClose}><X aria-hidden="true" /></button>
      </div>

    <main className={`admin-statement-sheet admin-statement-sheet-${paperSize}`} style={{ '--statement-font-size': `${fontSize}pt` } as React.CSSProperties}>
      <header className="admin-statement-heading">
        <div><span>Financial Health</span><h1 id="financial-statement-title">Statement of Assets and Liabilities</h1></div>
        <div><span>Data as of Today</span><strong>{today}</strong><small>Profile ID: {profile?.profileId || 'No active profile'}</small></div>
      </header>

      {!profile ? <div className="admin-statement-no-profile" role="status">No Build Profile data is available. Select or complete a profile, then use Refresh.</div> : null}

      <div className="admin-statement-grid">
        {renderStatement(false)}
        {renderStatement(true)}
        <aside className="admin-statement-gap-column">
          <header><span>Priority Analysis</span><h2>Top Gaps & AI Recommendations</h2></header>
          {topGaps.length > 0 ? topGaps.map((entry, index) => <article key={entry.id}>
            <div className="admin-statement-gap-title"><span>{index + 1}</span><strong>{entry.label}</strong></div>
            <dl>
              <div><dt>Current</dt><dd>{money.format(entry.current)}</dd></div>
              <div><dt>Desired</dt><dd>{money.format(entry.desired)}</dd></div>
              <div><dt>Gap</dt><dd>{entry.gap > 0 ? '+' : ''}{money.format(entry.gap)}</dd></div>
            </dl>
            <p><strong>AI recommendation</strong>{recommendationFor(entry.section, entry.gap, entry.label)}</p>
          </article>) : <div className="admin-statement-no-gaps">No current-to-desired gaps are available.</div>}
        </aside>
      </div>
      <footer>Planning statement based on the active Build Profile. AI recommendations require independent professional review.</footer>
    </main>
    </div>
  </div>, document.body)
}