import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { Printer, RefreshCw, X } from 'lucide-react'

import { readReplicatedBuildProfile, type ReplicatedBuildProfile } from '../scoring/buildProfileReplication'
import CreditHealthScoreGraph, { type CreditHealthGraphScores } from '../scoring/CreditHealthScoreGraph'
import type { FinancialHealthSummaryResult } from '../scoring/financialHealthSummaryEngine'
import { getFinancialHealthBand } from '../scoring/financialHealthModel'
import { NET_WORTH_STATEMENT_ENTRIES, type StatementSection } from '../scoring/NetWorthPositioningPage'
import { computeNetWorthBuildingScore } from '../scoring/netWorthBuildingEngine'
import WealthBalanceRadar from '../scoring/WealthBalanceRadar'
import { computeWealthFoundationScore } from '../scoring/wealthFoundationEngine'

import './AdminFinancialStatementPage.css'

type PaperSize = 'a4' | 'letter'

type SummaryRow = {
  category: string
  amount: number
}

const REPORT_SECTIONS: Array<{ section: StatementSection; label: string }> = [
  { section: 'assets', label: 'Assets' },
  { section: 'liabilities', label: 'Liabilities' },
  { section: 'monthly-income', label: 'Personal Income' },
  { section: 'monthly-expenses', label: 'Personal Expenses' },
]
const CURRENT_FINANCIAL_SECTIONS: Array<{ section: StatementSection; label: string }> = [
  { section: 'monthly-income', label: 'Personal Income' },
  { section: 'monthly-expenses', label: 'Personal Expenses' },
  { section: 'financial-goals', label: 'Goals' },
  { section: 'insurance-coverage', label: 'Protection (Insurance)' },
]

const toAmount = (value: string | undefined) => {
  const amount = Number(value)
  return Number.isFinite(amount) && amount > 0 ? amount : 0
}

function summarizeSection(profile: ReplicatedBuildProfile | null, section: StatementSection, desired: boolean): SummaryRow[] {
  if (!profile) return []

  const totals = new Map<string, number>()
  NET_WORTH_STATEMENT_ENTRIES
    .filter((entry) => entry.section === section && !entry.autoGenerated)
    .forEach((entry) => {
      const key = desired ? `wealthActual.${entry.id}` : entry.id
      totals.set(entry.category, (totals.get(entry.category) ?? 0) + toAmount(profile.values[key]))
    })

  return [...totals.entries()]
    .map(([category, amount]) => ({ category, amount }))
    .filter((row) => row.amount > 0)
}

function recommendationFor(section: StatementSection, gap: number, label: string) {
  const needsIncrease = gap > 0
  if (section === 'liabilities') {
    return needsIncrease
      ? `Review why desired ${label.toLowerCase()} is higher and avoid unnecessary borrowing.`
      : `Direct available surplus toward reducing ${label.toLowerCase()} on schedule.`
  }
  if (section === 'monthly-expenses') {
    return needsIncrease
      ? `Validate the planned increase in ${label.toLowerCase()} against monthly cash flow.`
      : `Reduce ${label.toLowerCase()} through a defined monthly spending limit.`
  }
  if (section === 'monthly-income') {
    return needsIncrease
      ? `Set a monthly action plan to grow ${label.toLowerCase()} toward the desired amount.`
      : `Protect the current ${label.toLowerCase()} level and reassess the target.`
  }
  return needsIncrease
    ? `Prioritize regular contributions to close the ${label.toLowerCase()} gap.`
    : `Preserve the current ${label.toLowerCase()} position and review allocation quality.`
}

type FinancialStatementModalProps = {
  onClose: () => void
  creditScores?: CreditHealthGraphScores
  financialHealthSummary: FinancialHealthSummaryResult
}

const EMPTY_CREDIT_SCORES: CreditHealthGraphScores = {
  credit: null,
  nonStarter: null,
  social: null,
  psychometric: null,
}

export default function FinancialStatementModal({
  onClose,
  creditScores = EMPTY_CREDIT_SCORES,
  financialHealthSummary,
}: FinancialStatementModalProps) {
  const [profile, setProfile] = useState(() => readReplicatedBuildProfile())
  const [paperSize, setPaperSize] = useState<PaperSize>('a4')
  const [fontSize, setFontSize] = useState(10)

  const currency = profile?.values.wealthCurrency || 'PHP'
  const money = useMemo(() => new Intl.NumberFormat('en', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0,
  }), [currency])
  const today = new Intl.DateTimeFormat('en', { dateStyle: 'long' }).format(new Date())

  useEffect(() => {
    setProfile(readReplicatedBuildProfile())
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', closeOnEscape)
    return () => document.removeEventListener('keydown', closeOnEscape)
  }, [onClose])

  const sectionRows = useMemo(() => Object.fromEntries(REPORT_SECTIONS.map(({ section }) => [
    section,
    {
      current: summarizeSection(profile, section, false),
      desired: summarizeSection(profile, section, true),
    },
  ])) as Record<StatementSection, { current: SummaryRow[]; desired: SummaryRow[] }>, [profile])

  const total = (section: StatementSection, desired: boolean) =>
    sectionRows[section][desired ? 'desired' : 'current'].reduce((sum, row) => sum + row.amount, 0)

  const currentNetWorth = total('assets', false) - total('liabilities', false)
  const desiredNetWorth = total('assets', true) - total('liabilities', true)
  const currentNetIncome = total('monthly-income', false) - total('monthly-expenses', false)
  const desiredNetIncome = total('monthly-income', true) - total('monthly-expenses', true)
  const financialHealthBand = getFinancialHealthBand(financialHealthSummary.score)
  const netWorthDraft = useMemo(() => ({
    amounts: Object.fromEntries(NET_WORTH_STATEMENT_ENTRIES
      .filter((entry) => !entry.autoGenerated)
      .map((entry) => [entry.id, profile?.values[entry.id] ?? ''])),
  }), [profile])
  const netWorthPositioning = useMemo(() => computeNetWorthBuildingScore(netWorthDraft).score, [netWorthDraft])
  const wealthFoundation = useMemo(() => computeWealthFoundationScore(netWorthDraft).score, [netWorthDraft])
  const suitabilityValues = Object.values(profile?.suitabilityAnswers ?? {}).map(Number).filter(Number.isFinite)
  const wealthBehaviour = suitabilityValues.length > 0
    ? Math.round((suitabilityValues.reduce((sum, value) => sum + value, 0) / suitabilityValues.length / 4) * 100)
    : 0
  const declaredEntries = NET_WORTH_STATEMENT_ENTRIES.filter((entry) => !entry.autoGenerated)
  const completedEntries = declaredEntries.filter((entry) => toAmount(profile?.values[entry.id]) > 0).length
  const wealthAuthenticity = declaredEntries.length > 0 ? Math.round((completedEntries / declaredEntries.length) * 100) : 0

  const topGaps = useMemo(() => NET_WORTH_STATEMENT_ENTRIES
    .filter((entry) => !entry.autoGenerated && REPORT_SECTIONS.some(({ section }) => section === entry.section))
    .map((entry) => {
      const current = toAmount(profile?.values[entry.id])
      const desired = toAmount(profile?.values[`wealthActual.${entry.id}`])
      return { ...entry, current, desired, gap: desired - current }
    })
    .filter((entry) => entry.gap !== 0)
    .sort((left, right) => Math.abs(right.gap) - Math.abs(left.gap))
    .slice(0, 5), [profile])

  const renderStatement = (desired: boolean) => (
    <section className="admin-statement-column">
      <header>
        <span>{desired ? 'Desired Position' : 'Current Position'}</span>
        <h2>{desired ? 'Desired Net Worth & Cash Flow' : 'Current Net Worth & Cash Flow'}</h2>
      </header>
      {REPORT_SECTIONS.map(({ section, label }) => {
        const rows = sectionRows[section][desired ? 'desired' : 'current']
        return <div className="admin-statement-section" key={section}>
          <h3>{label}</h3>
          {rows.length > 0 ? rows.map((row) => <div className="admin-statement-row" key={row.category}>
            <span>{row.category}</span><strong>{money.format(row.amount)}</strong>
          </div>) : <p className="admin-statement-empty">No amount entered</p>}
          <div className="admin-statement-total"><span>Total {label}</span><strong>{money.format(total(section, desired))}</strong></div>
        </div>
      })}
      <div className="admin-statement-key-totals">
        <div><span>Net Worth</span><strong>{money.format(desired ? desiredNetWorth : currentNetWorth)}</strong></div>
        <div><span>Net Monthly Income</span><strong>{money.format(desired ? desiredNetIncome : currentNetIncome)}</strong></div>
      </div>
    </section>
  )

  const currentFinancialRows = (section: StatementSection) => NET_WORTH_STATEMENT_ENTRIES
    .filter((entry) => entry.section === section && !entry.autoGenerated)
    .map((entry) => ({ ...entry, amount: toAmount(profile?.values[entry.id]) }))

  const renderCurrentFinancialSection = (section: StatementSection, label: string) => {
    const rows = currentFinancialRows(section)
    const categories = [...new Set(rows.map((row) => row.category))]
    const sectionTotal = rows.reduce((sum, row) => sum + row.amount, 0)

    return <section className={`admin-current-financial-section admin-current-financial-${section}`} key={section}>
      <header><h2>{label}</h2><strong>{money.format(sectionTotal)}</strong></header>
      <div className="admin-current-financial-lines">
        {categories.map((category) => <div className="admin-current-financial-group" key={category}>
          <h3>{category}</h3>
          {rows.filter((row) => row.category === category).map((row) => <div className="admin-current-financial-row" key={row.id}>
            <span>{row.label}</span><strong>{money.format(row.amount)}</strong>
          </div>)}
        </div>)}
      </div>
    </section>
  }

  const renderCurrentNetWorthSection = (section: 'assets' | 'liabilities', label: string) => {
    const rows = currentFinancialRows(section)
    const categories = [...new Set(rows.map((row) => row.category))]
    const sectionTotal = rows.reduce((sum, row) => sum + row.amount, 0)

    return <section className={`admin-current-net-worth-section admin-current-net-worth-${section}`}>
      <header><h2>{label}</h2><strong>{money.format(sectionTotal)}</strong></header>
      <div className="admin-current-net-worth-lines">
        {categories.map((category) => <div className="admin-current-net-worth-group" key={category}>
          <h3>{category}</h3>
          {rows.filter((row) => row.category === category).map((row) => <div className="admin-current-net-worth-row" key={row.id}>
            <span>{row.label}</span><strong>{money.format(row.amount)}</strong>
          </div>)}
        </div>)}
      </div>
    </section>
  }

  return createPortal(<div className="admin-financial-statement-overlay" role="dialog" aria-modal="true" aria-labelledby="financial-statement-title" onMouseDown={(event) => {
    if (event.target === event.currentTarget) onClose()
  }}>
    <div className="admin-financial-statement-page">
      <div className="admin-statement-toolbar" aria-label="Statement display controls">
      <label>Paper
        <select value={paperSize} onChange={(event) => setPaperSize(event.target.value as PaperSize)}>
          <option value="a4">A4</option>
          <option value="letter">Short coupon / Letter</option>
        </select>
      </label>
      <label>Font size
        <input type="range" min="8" max="14" step="1" value={fontSize} onChange={(event) => setFontSize(Number(event.target.value))} />
        <output>{fontSize} pt</output>
      </label>
      <button type="button" title="Refresh Build Profile data" onClick={() => setProfile(readReplicatedBuildProfile())}><RefreshCw aria-hidden="true" /> Refresh</button>
      <button type="button" title="Print financial statement" onClick={() => window.print()}><Printer aria-hidden="true" /> Print</button>
      <button type="button" title="Close financial statement" aria-label="Close financial statement" onClick={onClose}><X aria-hidden="true" /></button>
      </div>

    <div className="admin-statement-pages" style={{ '--statement-font-size': `${fontSize}pt` } as React.CSSProperties}>
    <main className={`admin-statement-sheet admin-statement-sheet-${paperSize} admin-statement-cover-sheet`}>
      <header className="admin-statement-heading">
        <div><span>Financial Health · Page 1</span><h1 id="financial-statement-title">Statement of Assets and Liabilities</h1></div>
        <div><span>Data as of Today</span><strong>{today}</strong><small>Profile ID: {profile?.profileId || 'No active profile'}</small></div>
      </header>

      <div className="admin-statement-cover-grid">
        <section className="admin-cover-position">
          <header><span>Current Position</span><h2>Current Net Worth &amp; Cash Flow</h2></header>
          {REPORT_SECTIONS.map(({ section, label }) => {
            const rows = sectionRows[section].current
            return <div className="admin-cover-position-section" key={section}>
              <h3>{label}</h3>
              {rows.length > 0 ? rows.map((row, index) => <div className="admin-cover-position-row" key={row.category}>
                <span>{index + 1}. {row.category}</span><strong>{money.format(row.amount)}</strong>
              </div>) : <p>No amount entered</p>}
              <div className="admin-cover-position-total"><span>Total {label}</span><strong>{money.format(total(section, false))}</strong></div>
            </div>
          })}
          <div className="admin-cover-position-results">
            <div><span>Net Worth</span><strong>{money.format(currentNetWorth)}</strong></div>
            <div><span>Net Monthly Income</span><strong>{money.format(currentNetIncome)}</strong></div>
          </div>
        </section>

        <section className="admin-cover-health" aria-label={`Financial Health score ${financialHealthSummary.score} out of 1000`}>
          <span className="admin-cover-kicker">FILSCORE Financial Vital Signs</span>
          <h2>Financial Health</h2>
          <div className="admin-cover-health-groups">
            {financialHealthSummary.groups.map((group) => <div key={group.id}><strong>{group.label}</strong><span>{group.description}</span></div>)}
          </div>
          <div className="admin-cover-health-band"><i /> <strong>{financialHealthBand}</strong><span>Financial health band</span></div>
          <div className="admin-cover-health-rings">
            {financialHealthSummary.groups.map((group, index) => <div key={group.id} className={`admin-cover-ring admin-cover-ring-${index + 1}`} style={{ '--cover-ring-progress': `${group.value * 3.6}deg` } as React.CSSProperties} />)}
            <div className="admin-cover-ring-score"><strong>{financialHealthSummary.score}</strong><span>/ 1000</span></div>
          </div>
          <div className="admin-cover-ring-legend"><span><i />Gold · Foundation</span><span><i />Silver · Controls</span><span><i />Bronze · Future</span></div>
        </section>

        <section className="admin-cover-credit">
          <CreditHealthScoreGraph scores={creditScores} />
          <div className="admin-cover-credit-footer"><span>FILSCORE</span><strong>{profile?.completionPercent ?? 0}% information provided</strong></div>
        </section>

        <section className="admin-cover-wealth">
          <WealthBalanceRadar
            netWorthPositioning={netWorthPositioning}
            wealthBehaviour={wealthBehaviour}
            wealthFoundation={wealthFoundation}
            wealthAuthenticity={wealthAuthenticity}
          />
        </section>
      </div>
      <footer>Consolidated financial position and health overview based on the active Build Profile.</footer>
    </main>

    <main className={`admin-statement-sheet admin-statement-sheet-${paperSize}`}>
      <header className="admin-statement-heading">
        <div><span>Financial Health · Page 2</span><h1>Statement of Assets and Liabilities</h1></div>
        <div><span>Data as of Today</span><strong>{today}</strong><small>Profile ID: {profile?.profileId || 'No active profile'}</small></div>
      </header>

      {!profile ? <div className="admin-statement-no-profile" role="status">No Build Profile data is available. Select or complete a profile, then use Refresh.</div> : null}

      <div className="admin-statement-grid">
        {renderStatement(false)}
        {renderStatement(true)}
        <aside className="admin-statement-gap-column">
          <header><span>Priority Analysis</span><h2>Top Gaps & AI Recommendations</h2></header>
          {topGaps.length > 0 ? topGaps.map((entry, index) => <article key={entry.id}>
            <div className="admin-statement-gap-title"><span>{index + 1}</span><strong>{entry.label}</strong></div>
            <dl>
              <div><dt>Current</dt><dd>{money.format(entry.current)}</dd></div>
              <div><dt>Desired</dt><dd>{money.format(entry.desired)}</dd></div>
              <div><dt>Gap</dt><dd>{entry.gap > 0 ? '+' : ''}{money.format(entry.gap)}</dd></div>
            </dl>
            <p><strong>AI recommendation</strong>{recommendationFor(entry.section, entry.gap, entry.label)}</p>
          </article>) : <div className="admin-statement-no-gaps">No current-to-desired gaps are available.</div>}
        </aside>
      </div>
      <footer>Planning statement based on the active Build Profile. AI recommendations require independent professional review.</footer>
    </main>

    <main className={`admin-statement-sheet admin-statement-sheet-${paperSize} admin-current-net-worth-sheet`}>
      <header className="admin-statement-heading">
        <div><span>Financial Health · Page 3</span><h1>Current Net Worth</h1></div>
        <div><span>Statement Date</span><strong>{profile?.values.asOfDate || today}</strong><small>Profile ID: {profile?.profileId || 'No active profile'}</small></div>
      </header>

      <div className="admin-current-page-note"><span>Enter all applicable assets and liabilities</span><strong>Actual/current values declared in Workflow Step 8</strong></div>
      <div className="admin-current-net-worth-grid">
        {renderCurrentNetWorthSection('assets', 'Assets')}
        {renderCurrentNetWorthSection('liabilities', 'Liabilities')}
      </div>
      <div className="admin-current-net-worth-results">
        <div><span>Total Assets</span><strong>{money.format(total('assets', false))}</strong></div>
        <div><span>Total Liabilities</span><strong>{money.format(total('liabilities', false))}</strong></div>
        <div><span>Current Net Worth</span><strong>{money.format(currentNetWorth)}</strong></div>
      </div>
      <footer>Actual/current values from Step 8 of the active Build Profile. Zero indicates no amount entered.</footer>
    </main>

    <main className={`admin-statement-sheet admin-statement-sheet-${paperSize} admin-current-financial-sheet`}>
      <header className="admin-statement-heading">
        <div><span>Financial Health · Page 4</span><h1>Actual / Current Personal Income and Expenses with Goals and Protection</h1></div>
        <div><span>Statement Date</span><strong>{profile?.values.asOfDate || today}</strong><small>Profile ID: {profile?.profileId || 'No active profile'}</small></div>
      </header>

      <div className="admin-current-financial-meta">
        <div><span>Long Term Financial Goal</span><strong>{profile?.values.financialGoal || 'Not selected'}</strong></div>
        <div><span>Target Amount</span><strong>{money.format(toAmount(profile?.values.targetAmount))}</strong></div>
        <div><span>Months to Achieve</span><strong>{profile?.values.targetMonths || 'Not set'}</strong></div>
      </div>

      <div className="admin-current-financial-grid">
        {CURRENT_FINANCIAL_SECTIONS.map(({ section, label }) => renderCurrentFinancialSection(section, label))}
      </div>

      <div className="admin-current-financial-results">
        <div><span>Total Monthly Income</span><strong>{money.format(total('monthly-income', false))}</strong></div>
        <div><span>Total Monthly Expenses</span><strong>{money.format(total('monthly-expenses', false))}</strong></div>
        <div><span>Net Monthly Income</span><strong>{money.format(currentNetIncome)}</strong></div>
      </div>
      <footer>Actual/current values from Step 8 of the active Build Profile. Zero indicates no amount entered.</footer>
    </main>
    </div>
    </div>
  </div>, document.body)
}